version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: on-failure
    volumes:
      - ./postgres:/var/lib/postgresql/data/

  python:
    build: ./python
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/src
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db

  nginx:
    image: nginx:1.17
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python
